module.exports = [
  { id: '690cd6d5', name: 'Burgess Hurry', location: 'Caribbean Netherlands' },
  { id: '2f0e52ea', name: 'Carpenter Bone', location: 'Bahrain' },
  { id: 'f5f92113', name: 'Miles Additional', location: 'Mali' },
  { id: 'fb00a8e0', name: 'Wolfe Weight', location: 'Haiti' },
  { id: 'd1180ca2', name: 'Lucas Burst', location: 'Madagascar' },
  { id: '51fbad10', name: 'Porter Dig', location: 'Djibouti' },
  { id: 'e78a4091', name: 'Hill Greatest', location: 'Pitcairn Islands' },
  { id: '132cbd51', name: 'Schmidt Observe', location: 'Greece' },
  { id: 'b4658da6', name: 'Brady Angry', location: 'Antigua & Barbuda' },
  { id: '9525816f', name: 'Watts Afternoon', location: 'Vietnam' },
  { id: '7bc30be7', name: 'Cooper Wish', location: 'Åland Islands' },
  { id: '6f2b03d9', name: 'Hanson Chart', location: 'Gabon' },
  { id: '19358e57', name: 'Franklin Sound', location: 'Seychelles' },
  { id: '39b30015', name: 'Nguyen Branch', location: 'Iraq' },
  { id: '81582737', name: 'Fields Mood', location: 'Cook Islands' },
  { id: '3ffacde4', name: 'Silva Adult', location: 'Lebanon' },
  { id: 'b6c3b4d9', name: 'Jones Terrible', location: 'Mayotte' },
  { id: '86f6682f', name: 'Rowe Motor', location: 'Costa Rica' },
  { id: 'b9044ccd', name: 'Baldwin Manufacturing', location: 'Vatican City' },
  { id: 'ae220520', name: 'Colon Speech', location: 'Venezuela' },
  { id: '3cc7b6a9', name: 'Perkins Wise', location: 'Austria' },
  { id: '7fea289f', name: 'Meyer Port', location: 'St. Barthélemy' },
  { id: 'd8d52f3b', name: 'Morgan Slave', location: 'Bosnia & Herzegovina' },
  { id: 'f257d959', name: 'Love Dish', location: 'Tajikistan' },
  { id: '3e01a5ef', name: 'Garner Blue', location: 'Slovakia' },
  { id: '2511681d', name: 'Clark Managed', location: 'Turkmenistan' },
  { id: '0f282d4b', name: 'Holloway She', location: 'Niger' },
  { id: 'df19739b', name: 'McLaughlin History', location: 'Bhutan' },
  { id: '3f05a95a', name: 'Spencer Include', location: 'Canada' },
  { id: 'abac3cf6', name: 'Bradley Instance', location: 'Andorra' },
  { id: 'e52adf16', name: 'Morton Slip', location: 'Mongolia' },
  { id: '877cc835', name: 'Andrews Up', location: 'Macau SAR China' },
  { id: '4cbd35ac', name: 'Phillips Brown', location: 'Nepal' },
  { id: '28337eda', name: 'Doyle Blow', location: 'Montserrat' },
  { id: 'b1d8ee5c', name: 'Wolfe Seeing', location: 'Botswana' },
  { id: 'd81d316c', name: 'Henderson Bark', location: 'Estonia' },
  { id: '69de051a', name: 'Abbott Yes', location: 'Zimbabwe' },
  { id: '6296eeba', name: 'Lawrence Individual', location: 'Mongolia' },
  { id: '13809edc', name: 'Schmidt Late', location: 'Madagascar' },
  { id: 'b09f9a8f', name: 'McGee Clothes', location: 'Guam' },
  { id: 'f50d4f88', name: 'Briggs Silly', location: 'Angola' },
  { id: 'd80eac92', name: 'Townsend Watch', location: 'Mauritius' },
  { id: 'df1cf0b6', name: 'Doyle Especially', location: 'Taiwan' },
  { id: '41af4ba8', name: 'Shaw Article', location: 'Ireland' },
  { id: 'ce03be8b', name: 'Ford Possible', location: 'South Georgia & South Sandwich Islands' },
  { id: '8bba9706', name: 'Tucker Difficulty', location: 'Rwanda' },
  { id: 'c35ae55b', name: 'Roberts Listen', location: 'United States' },
  { id: '1bf86809', name: 'Jensen Substance', location: 'Monaco' },
  { id: '55c80698', name: 'Rivera Excellent', location: 'Micronesia' },
  { id: '5a9a1240', name: 'Elliott Thee', location: 'Caribbean Netherlands' },
  { id: 'dc0705c5', name: 'Dawson Must', location: 'South Sudan' },
  { id: '2b0334af', name: 'Zimmerman Bar', location: 'Ghana' },
  { id: 'ce4ace66', name: 'Hamilton Night', location: 'French Southern Territories' },
  { id: '165d27ac', name: 'Morales Route', location: 'Bahrain' },
  { id: 'e4b4feec', name: 'Powell Apartment', location: 'Gibraltar' },
  { id: '49773b12', name: 'Williamson Daily', location: 'Samoa' },
  { id: 'ef1d399c', name: 'Harris Sent', location: 'Uzbekistan' },
  { id: '01665553', name: 'Reid Proud', location: 'Panama' },
  { id: '05ad907b', name: 'Hudson Correct', location: 'Latvia' },
  { id: '1f247a65', name: 'Robbins Action', location: 'Bermuda' },
  { id: '6e432eb7', name: 'Crawford Red', location: 'Congo - Brazzaville' },
  { id: 'de3d7ae6', name: 'Reese Lovely', location: 'South Africa' },
  { id: 'bb177272', name: 'Sharp Fill', location: 'Ukraine' },
  { id: '68fbc2a6', name: 'Malone Sugar', location: 'Venezuela' },
  { id: '94346e81', name: 'Bell Sand', location: 'Timor-Leste' },
  { id: '7fcf6f3f', name: 'Casey Promised', location: 'Cyprus' },
  { id: '7fcf2b8c', name: 'Carpenter Guide', location: 'Burundi' },
  { id: '58755e7e', name: 'Marshall Root', location: 'Iceland' },
  { id: '737fb8af', name: 'Wilkerson Furniture', location: 'South Africa' },
  { id: 'e5a79533', name: 'Burke Engine', location: 'Russia' },
  { id: '9d0ce2a4', name: 'Figueroa Hang', location: 'Gabon' }
]
